# Generated by Django 4.2.6 on 2023-10-30 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 30, 20, 16, 28, 220718)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ManyToManyField(blank=True, null=True, to="core.productimage"),
        ),
        migrations.AlterField(
            model_name="product",
            name="published_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 30, 20, 16, 28, 220738)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 30, 20, 16, 28, 220743)
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 30, 20, 16, 28, 221296)
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 30, 20, 16, 28, 221388)
            ),
        ),
    ]
