# Generated by Django 4.2.6 on 2023-11-02 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_product_created_at_alter_product_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publish_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 2, 21, 33, 47, 936547)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="published_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 2, 21, 33, 47, 936564)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 2, 21, 33, 47, 936629)
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 2, 21, 33, 47, 937148)
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 2, 21, 33, 47, 937247)
            ),
        ),
    ]
